### PR TITLE
 Modify versionName regex to support single quotes

### LINKED ISSUE #61: Not updating build.gradle versionName if existing value uses single quotes
Description is all in the title! `build.gradle` is a groovy file, and so both [single](http://groovy-lang.org/syntax.html#_single_quoted_string) and [double](http://groovy-lang.org/syntax.html#_double_quoted_string) quotes can be used. if your `build.gradle` has `versionName` defined with single quotes, it fails to update.

Thanks!

### PR DESCRIPTION
**Pull request by Leeds-eBooks**
Fixes #61

### CODE REVIEW

**Comment by stovmascript** [comment]
Great! Please rebase this into one commit and run `npm install` or `yarn` before doing that.

**Comment by stovmascript** [comment]
Nevermind, looks like a rebase doesn't trigger pre-commit anyway.

**Comment by stovmascript** [comment]
Thanks for you contribution. Merging and releasing this now.

**Comment by Leeds-eBooks** [comment]
Sorry, I was going to get to this today, but thanks for doing that!

**Pull request merged**
