### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vonovak**
just a small note on customizing the commit message with yarn

### CODE REVIEW

**Comment by stovmascript** [comment]
I tested both `npm` (v6.7.0) and `yarn` (v1.12.3) and it seems to work ok. Check it our here: https://github.com/stovmascript/AwesomeProjectForTestingRNV/releases. The first 2 versions were made with npm and the last 4 with Yarn. Versioning was done with the [basic RNV setup](https://github.com/stovmascript/AwesomeProjectForTestingRNV/blob/master/package.json#L8) Everything seems the same, so I wonder if there's something specific with your machine.

Here are my configs:

```
$ npm config list -l
; cli configs
long = true
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.7.0 node/v11.10.0 darwin x64"

; userconfig /Users/martin/.npmrc
scripts-prepend-node-path = true

; default values
access = null
allow-same-version = false
also = null
always-auth = false
audit = true
audit-level = "low"
auth-type = "legacy"
bin-links = true
browser = null
ca = null
cache = "/Users/martin/.npm"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
dry-run = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/Users/martin/.nvm/versions/node/v11.10.0/etc/npmrc"
globalignorefile = "/Users/martin/.nvm/versions/node/v11.10.0/etc/npmignore"
group = 20
ham-it-up = false
heading = "npm"
https-proxy = null
if-present = false
ignore-prepublish = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/Users/martin/.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "notice"
logs-max = 10
; long = false (overridden)
maxsockets = 50
message = "%s"
; metrics-registry = null (overridden)
node-options = null
node-version = "11.10.0"
noproxy = null
offline = false
onload-script = null
only = null
optional = true
otp = null
package-lock = true
package-lock-only = false
parseable = false
prefer-offline = false
prefer-online = false
prefix = "/Users/martin/.nvm/versions/node/v11.10.0"
preid = ""
production = false
progress = true
proxy = null
read-only = false
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
; scripts-prepend-node-path = "warn-only" (overridden)
searchexclude = null
searchlimit = 20
searchopts = ""
searchstaleness = 900
send-metrics = false
shell = "/bin/bash"
shrinkwrap = true
sign-git-commit = false
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "/var/folders/cr/q0qccvm9601_8kgkvckm9rjh0000gn/T"
umask = 18
unicode = false
unsafe-perm = true
update-notifier = true
usage = false
user = 501
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "/Users/martin/.npmrc"
version = false
versions = false
viewer = "man"
```

```
$ yarn config list
yarn config v1.12.3
info yarn config
{ 'version-tag-prefix':
   'v',
  'version-git-tag':
   true,
  'version-commit-hooks':
   true,
  'version-git-sign':
   false,
  'version-git-message':
   'v%s',
  'init-version':
   '1.0.0',
  'init-license':
   'MIT',
  'save-prefix':
   '^',
  'bin-links':
   true,
  'ignore-scripts':
   false,
  'ignore-optional':
   false,
  registry:
   'https://registry.yarnpkg.com',
  'strict-ssl':
   true,
  'user-agent':
   'yarn/1.12.3 npm/? node/v11.10.0 darwin x64',
  lastUpdateCheck:
   1555415607617 }
info npm config
{ '//registry.npmjs.org/:_authToken':
   '2026ccf5-44d3-438a-8d23-dfe385cb1b99',
  'scripts-prepend-node-path':
   true,
  python:
   '/usr/bin/python' }
Done in 0.07s.
```

```
$ yarn config current
yarn config v1.12.3
{
  "rootModuleFolders": [
    "/Users/martin/AwesomeProjectForTestingRNV/node_modules"
  ],
  "registryFolders": [
    "node_modules"
  ],
  "linkedModules": [],
  "cache": {},
  "cwd": "/Users/martin/AwesomeProjectForTestingRNV",
  "looseSemver": true,
  "commandName": "config",
  "preferOffline": false,
  "globalFolder": "/Users/martin/.config/yarn/global",
  "linkFolder": "/Users/martin/.config/yarn/link",
  "offline": false,
  "binLinks": true,
  "ignorePlatform": false,
  "ignoreScripts": false,
  "disablePrepublish": false,
  "nonInteractive": true,
  "workspaceRootFolder": null,
  "lockfileFolder": "/Users/martin/AwesomeProjectForTestingRNV",
  "networkConcurrency": 8,
  "childConcurrency": 5,
  "networkTimeout": 30000,
  "workspacesEnabled": true,
  "workspacesNohoistEnabled": true,
  "pruneOfflineMirror": false,
  "enableMetaFolder": false,
  "enableLockfileVersions": false,
  "linkFileDependencies": false,
  "cacheFolder": "/Users/martin/Library/Caches/Yarn/v4",
  "tempFolder": "/Users/martin/Library/Caches/Yarn/v4/.tmp",
  "production": false
}
Done in 0.07s.
```

**Comment by vonovak** [comment]
@stovmascript I used an old version that had this issue because I was using a custom commit message, so feel free to ignore that part of the comment (I removed it). This PR should be good to go as-is, thanks

**Comment by stovmascript** [comment]
Do you think it's necessary though? That section was only meant to illustrate how to work with custom commit messages. We aren't educating people how to config npm, so why should we do it for Yarn users?

It just seems like we're repeating something that's already in the docs of npm/Yarn (and could potentially change, making our copy outdated).

**Comment by vonovak** [comment]
I think most people don't know `npm / yarn version` very well. Customizing the commit message will probably be a fairly common use case and I would find it nice to have it documented right here without having to google for it (frankly, it took me while to discover the npmrc option).

I don't think the config option will change, given how many people will depend on it.

Do as you like :)

**Pull request merged**
