### PR TITLE
Increment build number was not consistent

### PR DESCRIPTION
**Pull request by adebree**
See pull, the -b flag was slightly inconsitent. I've changed the description from 'only update buildnumber' to 'also update buildnumber' and changed the code accordingly.

### CODE REVIEW

**Comment by stovmascript** [comment]
Interesting, what is your use case?

I'm asking because to be honest, I sneaked this feature in with the intent of standalone usage, for the moment you only need to increment the build number on say iOS (`react-native-version -bt ios`) for submitting a new build to TestFlight for example.

Was the build number not being incremented by default?

P.S. I am already thinking of improving this functionality even more becase I think it should also take the CURRENT_PROJECT_VERSION variable into account in Xcode projects, which is sometimes used even outside of Xcode (fastlane's increment_build_number for example).

**Comment by adebree** [comment]
We needed / used it in a nightly build to testflight / playstore / testobject use case and wanted to bump the versions in a single CI (Jenkins) job which kicked off a build and deploy jobs for android and ios.

Main issue with react-native-version was that when not specifying -b CFBundleVersion was always set to "1" (and overwriting any previously. But when setting -b *only* CFBundleShortVersionString was set to package.version, so that didn't fit the description of the -b flag either. So it was a 'cant win' situation ;)

**Comment by stovmascript** [comment]
Yeah, now I see that it's definitely weird behaviour. It originates from the fact that Android's versionCode always needs to be bumped, but for iOS the CFBundleVersion only needs to be bumped when uploading a build with a same CFBundleShortVersionString, so I thought it would be better to reset it back to 1 every time the CFBundleShortVersionString is bumped - which is indeed inconsistent.

Thanks for your contribution and explaining your usage. I will look into merging this in the evening.

I'll also look into streamlining it more with the notes mentioned above.

**Comment by stovmascript** [comment]
Hey @adebree, please check out the new version on npm. It's v2, as I've introduced some [breaking changes](https://github.com/stovmascript/react-native-version/releases/tag/v2.0.0). It should now be bumping build numbers consistently across platforms, but with the same settings as before. In the end, I didn't merge your PR because it would change the functionality of an option I wanted to retain - being able to just bump build numbers. I was also already making some changes under the hood, so I went with my implementation. Sorry for not merging your code in the end, but thank you for bringing up an issue which would've otherwise probably gone unnoticed by me.

**Pull request closed without merging**
